### ISSUE TITLE
Lambda throwing error

### ISSUE THREAD

**Issue by humbertowoody** [AndreyMarchuk/code-pipeline-slack#5]
Hi! I tried to run the repo but got no luck. These are the steps I followed:

1. Cloned Repo
2. Set S3 environment variables 
3. Uncommented the bottom lines on `package.sh`
3. Ran `package.sh` (it seemed to have runned `pip install` correctly, packaged the cloudformation and uploaded it to S3)
4. Bucket ended with 2 files: `template.yml` and `f03d8c4139a59ac8dc41173a573f7373`.
5. Ran the CloudFormation with the S3 URL pointing to my `template.yml` and supplied the Slack tokens and variables.
6. Stack created successfully, everything seems normal. Push something and trigger CodePipeline, go check Slack and nothing happens. 

Lambda runs with error, as described by CloudWatch:

`Unable to import module 'notifier': No module named slackclient`

Am I missing something here? Is there an issue whilst packaging the lambda with `pip`'s dependencies? Maybe dependencies not making it to S3? 

Thanks in advance. Your fork seems to have solved several issues with original one :)

**Comment by LinguineCode** [comment]
The fix for this is already in the original/upstream repo: https://github.com/ogrodnek/code-pipeline-slack/blob/master/requirements.txt

Does @AndreyMarchuk plan to rebase against upstream repo?

**Comment by AndreyMay** [comment]
Thanks, rebased and closing the issue.

**Comment by AndreyMarchuk** [comment]
Thanks, rebased and closing the issue.
